import { _electron as electron } from '@playwright/test';
import assert from 'node:assert/strict';
import http from 'node:http';
import https from 'node:https';
import net from 'node:net';
import dgram from 'node:dgram';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs/promises';
import { randomUUID, X509Certificate } from 'node:crypto';

const root = process.cwd();
const dataDir = path.join(root, '.test-data', randomUUID());
const review = path.join(root, '.impeccable', 'review');
await fs.mkdir(dataDir, { recursive: true }); await fs.mkdir(review, { recursive: true });
let country = 'US', overrideTimezone = '', proxyRequests = 0, directRequests = 0, authenticationChallenges = 0;
let browserHeaders, checkRateLimited = false, tunnelRateLimited = false;
let geoRequests = 0, rateLimitHits = 0;
const keyFile = path.join(dataDir, 'fixture-key.pem'), certFile = path.join(dataDir, 'fixture-cert.pem');
execFileSync(process.env.OPENSSL_BIN || 'C:\\Program Files\\Git\\usr\\bin\\openssl.exe', ['req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-keyout', keyFile, '-out', certFile, '-days', '1', '-subj', '/CN=RegionDesk local fixture', '-addext', 'subjectAltName=IP:127.0.0.1,DNS:regiondesk.test,DNS:regiondesk-frame.test'], { stdio: 'ignore' });
const cert = await fs.readFile(certFile), key = await fs.readFile(keyFile);
const fingerprint = new X509Certificate(cert).fingerprint256;
const tunnels = new Set(), tunnelPorts = new Set();
const fixture = https.createServer({ key, cert }, (req, res) => {
  if (req.url === '/login-redirect') { res.writeHead(302, { Location: '/page?logged-in=1' }); res.end(); return; }
  if (req.url === '/missing') { res.writeHead(404, { 'Content-Type': 'text/html' }); res.end('<h1>Fixture page not found</h1>'); return; }
  if (req.url === '/page') browserHeaders = { language: req.headers['accept-language'] };
  if (!tunnelPorts.has(req.socket.remotePort)) directRequests++;
  if (req.url === '/geo') { geoRequests++; if (checkRateLimited) { res.writeHead(429, {'Retry-After':'5'}); res.end(); return; } res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify({ success: true, ip: '203.0.113.42', country_code: country, city: country === 'US' ? 'New York' : 'London', timezone: { id: overrideTimezone || (country === 'US' ? 'America/New_York' : 'Europe/London') }, connection: { isp: 'LOCAL TEST FIXTURE — not a real proxy' } })); return; }
  if (req.url === '/worker.js') { res.setHeader('Content-Type', 'text/javascript'); res.end('postMessage({language:navigator.language,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,locale:Intl.DateTimeFormat().resolvedOptions().locale,userAgent:navigator.userAgent,clientHints:navigator.userAgentData?.toJSON()})'); return; }
  if (req.url === '/frame') { res.setHeader('Content-Type', 'text/html'); res.end('<script>parent.postMessage({language:navigator.language,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,clientHints:navigator.userAgentData?.toJSON()},"*")</script>'); return; }
  res.setHeader('Content-Type', 'text/html');
  res.end('<!doctype html><html><head><title>Local verification fixture</title></head><body style="background:#172023;color:#eff;font:16px sans-serif;padding:36px"><h1>Local browser test</h1><p>This page is a local test fixture, not TikTok or a US connection.</p><input id="upload" type="file"><a href="/next">Next page</a><button onclick="window.open(\'/popup\')">Popup</button></body></html>');
});
await new Promise(resolve => fixture.listen(0, '127.0.0.1', resolve));
const base = `https://regiondesk.test:${fixture.address().port}`;
const username = 'fixture-user', password = 'fixture-secret@with:punctuation';
const auth = `Basic ${Buffer.from(`${username}:${password}`).toString('base64')}`;
const upstream = http.createServer((req, res) => {
  if (req.headers['proxy-authorization'] !== auth) { authenticationChallenges++; res.writeHead(407, { 'Proxy-Authenticate': 'Basic realm="fixture"' }); res.end(); return; }
  proxyRequests++;
  const url = new URL(req.url);
  const headers = { ...req.headers, 'x-regiondesk-fixture-proxy': 'yes' }; delete headers['proxy-authorization'];
  const proxied = http.request(url, { method: req.method, headers }, response => { res.writeHead(response.statusCode, response.headers); response.pipe(res); });
  proxied.on('error', () => { res.writeHead(502); res.end(); }); req.pipe(proxied);
});
upstream.on('connect', (req, client, head) => {
  if (tunnelRateLimited) { rateLimitHits++; client.end('HTTP/1.1 429 Too Many Requests\r\nRetry-After: 5\r\n\r\n'); return; }
  if (req.headers['proxy-authorization'] !== auth) { authenticationChallenges++; client.end('HTTP/1.1 407 Proxy Authentication Required\r\nProxy-Authenticate: Basic realm="fixture"\r\n\r\n'); return; }
  const destination = new URL(`http://${req.url}`);
  if (!['127.0.0.1', 'regiondesk.test', 'regiondesk-frame.test'].includes(destination.hostname) || Number(destination.port) !== fixture.address().port) { client.end('HTTP/1.1 403 Forbidden\r\n\r\n'); return; }
  proxyRequests++;
  const remote = net.connect({ host: '127.0.0.1', port: Number(destination.port) });
  tunnels.add(client); tunnels.add(remote);
  remote.on('connect', () => { tunnelPorts.add(remote.localPort); client.write('HTTP/1.1 200 Connection Established\r\n\r\n'); if (head.length) remote.write(head); client.pipe(remote); remote.pipe(client); });
  client.on('error', () => remote.destroy()); remote.on('error', () => client.destroy());
  client.on('close', () => { tunnels.delete(client); remote.destroy(); }); remote.on('close', () => { tunnels.delete(remote); client.destroy(); });
});
await new Promise(resolve => upstream.listen(0, '127.0.0.1', resolve));
const proxyPort = upstream.address().port;
const stun = dgram.createSocket('udp4');
let directStunPackets = 0;
stun.on('message', () => directStunPackets++);
await new Promise(resolve => stun.bind(0, '127.0.0.1', resolve));
let app, page;
const passes = [];
const pass = message => { passes.push(message); console.log(`PASS ${message}`); };
const launch = async () => {
  app = await electron.launch({ args: ['.'], cwd: root, env: { ...process.env, REGIONDESK_TEST: '1', REGIONDESK_TEST_DATA: dataDir, REGIONDESK_CHECK_URL: `${base}/geo`, REGIONDESK_TEST_CERT_SHA256: fingerprint, ELECTRON_DISABLE_SECURITY_WARNINGS: 'true' }, timeout: 30000 });
  app.process().stderr.on('data', chunk => { if (/Error|Unhandled|Exception/.test(String(chunk))) console.error(String(chunk).replaceAll(password, '[redacted]')); });
  app.process().stdout.on('data', chunk => process.stdout.write(String(chunk).replaceAll(password, '[redacted]')));
  page = await app.firstWindow(); await page.waitForSelector('h1');
};
const api = async (method, arg) => {
  let timer;
  try { return await Promise.race([page.evaluate(([name, value]) => window.regiondesk[name](value), [method, arg]), new Promise((_, reject) => { timer = setTimeout(() => reject(new Error(`API timeout: ${method}`)), 25000); })]); }
  finally { clearTimeout(timer); }
};
const guest = async expression => app.evaluate(async ({ webContents }, { code, url }) => {
  const wc = webContents.getAllWebContents().find(w => w.getURL() === url);
  if (!wc) throw new Error('No guest page');
  return wc.executeJavaScript(code);
}, { code: expression, url: (await api('getState')).runtime.url });
const waitGuest = () => page.waitForFunction(async () => { const s = await window.regiondesk.getState(); return !!s.runtime.url && !s.runtime.loading; });
const capture = async name => {
  if (process.env.REGIONDESK_CAPTURE !== '1') return;
  await page.evaluate(() => document.fonts.ready);
  await page.waitForTimeout(250);
  await page.screenshot({ path: path.join(review, name), fullPage: true, animations: 'disabled' });
};
try {
  await launch();
  assert.equal((await api('getState')).runtime.status, 'locked');
  assert.equal(await page.getByText('Connection budget', { exact: true }).count(), 0);
  await assert.rejects(() => api('navigate', `${base}/page`), /Verify/); pass('fresh install blocks account browsing without a verified proxy');
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setContentSize(1440, 900));
  await capture('desktop.png');
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setContentSize(1060, 740));
  await capture('desktop-compact.png');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setContentSize(1440, 900));
  await page.getByRole('button', { name: 'Connections', exact: true }).click();
  assert.equal(await page.getByLabel('Estimated monthly cost (USD)').count(), 0);
  await capture('connections.png');
  await page.getByRole('button', { name: 'Profiles', exact: true }).click();
  await capture('profiles.png');
  await page.getByText('Advanced regional settings and permissions', {exact:true}).click();
  await page.getByLabel('Camera permission').scrollIntoViewIfNeeded();
  await capture('profile-permissions.png');
  await page.getByRole('button', { name: 'Diagnostics', exact: true }).click();
  await capture('diagnostics.png');
  await page.getByRole('button', { name: 'History', exact: true }).first().click();
  await capture('history-empty.png');
  pass('all five app screens render at supported desktop sizes');
  await page.getByRole('button', { name: 'Profiles', exact: true }).click();
  await page.getByText('Advanced regional settings and permissions', {exact:true}).click();
  const blocked = page.getByRole('radio', { name: /Block location requests/ });
  const configured = page.getByRole('radio', { name: /Use configured coordinates/ });
  assert.equal(await blocked.isChecked(), true);
  await blocked.focus(); await page.keyboard.press('ArrowRight');
  assert.equal(await configured.isChecked(), true);
  await page.getByLabel('Profile name', { exact: true }).fill('Unsaved test profile');
  await app.evaluate(({ dialog }) => { globalThis.regiondeskOriginalDialog = dialog.showMessageBox; dialog.showMessageBox = async () => ({ response: 0, checkboxChecked: false }); });
  await page.getByRole('button', { name: 'Connections', exact: true }).click();
  assert.equal(await page.getByLabel('Profile name', { exact: true }).inputValue(), 'Unsaved test profile');
  await page.getByRole('button', { name: 'New profile', exact: true }).click();
  assert.equal((await api('getState')).profiles.length, 1);
  assert.equal(await page.getByLabel('Profile name', { exact: true }).inputValue(), 'Unsaved test profile');
  await app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 1, checkboxChecked: false }); });
  await page.getByRole('button', { name: 'Connections', exact: true }).click();
  await page.getByLabel('Proxy host', { exact: true }).waitFor();
  await app.evaluate(({ dialog }) => { dialog.showMessageBox = globalThis.regiondeskOriginalDialog; delete globalThis.regiondeskOriginalDialog; });
  assert.equal((await api('getState')).profiles[0].name, 'United States');
  pass('unsaved edits survive cancelled navigation/creation; explicit discard transitions; location radios support arrow keys');
  let data = await api('getState'); const a = data.profiles[0];
  await page.getByRole('button', { name: 'Connections', exact: true }).click();
  await page.getByLabel('Proxy host', { exact: true }).fill('127.0.0.1');
  await page.getByLabel('Port', { exact: true }).fill(String(proxyPort));
  await page.getByLabel('Username', { exact: true }).fill(username);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByLabel('Provider label', { exact: true }).fill('Local verification fixture');
  assert.equal(await page.getByRole('button', { name: 'Check saved connection', exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: 'Save and connect', exact: true }).click();
  await page.waitForFunction(async () => (await window.regiondesk.getState()).runtime.status === 'ready');
  pass('connection form saves credentials and prevents verification of unsaved edits');
  await api('navigate', `${base}/page`);
  await page.waitForTimeout(500);
  await waitGuest();
  const retainedTab = (await api('getState')).browsing.activeTabId;
  await guest("globalThis.resilienceMarker = 'retained'; true");
  await api('newTab', 'https://unavailable.invalid/');
  await page.waitForTimeout(600);
  assert.equal((await api('getState')).runtime.status, 'ready', 'One rejected destination must not disconnect the profile');
  assert.match((await api('getState')).runtime.pageError.code, /TUNNEL/);
  await page.getByRole('button', { name: 'Browser', exact: true }).click();
  await page.getByRole('heading', { name: 'This page couldn’t open' }).waitFor();
  await capture('page-error.png');
  await api('browserAction', 'detach');
  let errorWindow;
  for (let i = 0; i < 30; i++) { errorWindow = app.windows().find(w => w.url().endsWith('#floating')); if (errorWindow) break; await page.waitForTimeout(50); }
  assert.ok(errorWindow);
  await errorWindow.getByRole('heading', { name: 'This page couldn’t open' }).waitFor();
  await app.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('#floating')).setContentSize(600, 500));
  assert.equal(await errorWindow.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  if (process.env.REGIONDESK_CAPTURE === '1') await errorWindow.screenshot({path:path.join(review, 'page-error-floating.png')});
  await api('browserAction', 'dock');
  await api('selectTab', retainedTab);
  assert.equal((await api('getState')).runtime.pageError, undefined);
  assert.equal(await guest('globalThis.resilienceMarker'), 'retained');
  await api('selectTab', (await api('getState')).browsing.tabs.at(-1).id);
  await api('closeTab', (await api('getState')).browsing.activeTabId);
  await api('selectTab', retainedTab);
  assert.equal(await guest('globalThis.resilienceMarker'), 'retained');
  pass('destination tunnel failure preserves the verified connection and other tabs');
  await api('navigate', 'https://[');
  assert.equal((await api('getState')).runtime.pageError.code, 'ERR_INVALID_URL');
  await page.locator('.page-error').getByRole('button', { name: 'Go back', exact: true }).click();
  assert.equal(await guest('globalThis.resilienceMarker'), 'retained');
  await guest("window.open('https://popup-unavailable.invalid/'); true");
  await page.waitForTimeout(500);
  assert.equal((await api('getState')).runtime.status, 'ready');
  assert.ok((await api('getState')).runtime.pageError);
  const recoveryURL = `${base.replace('regiondesk.test', 'regiondesk-frame.test')}/recovered`;
  await api('navigate', recoveryURL); await page.waitForTimeout(400);
  assert.equal((await api('getState')).runtime.pageError, undefined);
  const crashId = await app.evaluate(({webContents}, url) => webContents.getAllWebContents().find(w => w.getURL() === url).id, recoveryURL);
  await app.evaluate(({webContents}, id) => webContents.fromId(id).forcefullyCrashRenderer(), crashId);
  await page.waitForFunction(async () => !!(await window.regiondesk.getState()).runtime.pageError);
  assert.equal((await api('getState')).runtime.status, 'ready');
  await page.getByRole('button', { name: 'Reload page', exact: true }).click();
  await page.waitForTimeout(500);
  assert.equal((await api('getState')).runtime.pageError, undefined);
  assert.equal(await guest('navigator.language'), 'en-US');
  await api('closeTab', (await api('getState')).browsing.activeTabId);
  await api('selectTab', retainedTab);
  assert.equal(await guest('globalThis.resilienceMarker'), 'retained');
  await guest("for(let i=0;i<12;i++){const f=document.createElement('iframe');f.src='/frame?login='+i;document.body.append(f);setTimeout(()=>f.remove(),i*4);} true");
  await page.waitForTimeout(300);
  assert.equal((await api('getState')).runtime.status, 'ready');
  assert.equal((await api('getState')).runtime.pageError, undefined);
  pass('invalid addresses, failed popups, renderer crashes and short-lived login frames stay local and recover');
  await api('navigate', `${base}/login-redirect`); await page.waitForTimeout(400);
  assert.equal((await api('getState')).runtime.url, `${base}/page?logged-in=1`);
  assert.equal((await api('getState')).runtime.pageError, undefined);
  await api('navigate', `${base}/missing`); await page.waitForTimeout(400);
  assert.equal(await guest('document.querySelector("h1").textContent'), 'Fixture page not found');
  assert.equal((await api('getState')).runtime.pageError, undefined);
  await api('navigate', `${base}/page`); await page.waitForTimeout(400);
  pass('login redirects and website HTTP error pages render without disconnecting');
  const plus = await page.getByRole('button', {name:'New tab',exact:true}).boundingBox();
  const lastTab = await page.locator('.browser-tab').last().boundingBox();
  assert.ok(Math.abs(plus.x - lastTab.x - lastTab.width) < 3, 'New-tab button should follow the last tab');
  await page.getByRole('button', {name:'Bookmark this page',exact:true}).click();
  const countBeforeBookmark = (await api('getState')).browsing.tabs.length;
  await page.locator('.bookmark-item > button').first().click();
  assert.equal((await api('getState')).browsing.tabs.length, countBeforeBookmark + 1);
  await api('closeTab', (await api('getState')).browsing.activeTabId);
  await api('selectTab', retainedTab);
  await page.getByRole('button', {name:'Remove bookmark',exact:true}).click();
  pass('plus follows existing tabs and saved bookmarks open a new tab');
  const savedProfile = (await api('getState')).profiles[0];
  await api('saveProfile', { ...savedProfile, password: 'invalid-fixture-password' });
  const rejected = await api('verify');
  assert.equal(rejected.runtime.status, 'error');
  assert.match(rejected.runtime.message, /Proxy authentication failed.*HTTP 407/);
  assert.doesNotMatch(JSON.stringify(rejected), /invalid-fixture-password/);
  await api('saveProfile', { ...savedProfile, password });
  pass('upstream HTTP 407 surfaces a precise authentication error without leaking credentials');
  checkRateLimited = true;
  data = await api('verify');
  assert.equal(data.runtime.status, 'error'); assert.match(data.runtime.message, /region-check service.*429/);
  await assert.rejects(() => api('navigate', `${base}/page`), /Verify/);
  checkRateLimited = false;
  await page.waitForTimeout(6200);
  assert.equal((await api('getState')).runtime.status, 'ready');
  pass('startup 429 remains locked and automatically verifies after Retry-After');
  data = await api('verify');
  assert.equal(data.runtime.status, 'ready', data.runtime.message);
  assert.equal(data.runtime.network.country, 'US');
  assert.equal(data.runtime.browser.timezone, 'America/New_York');
  assert.equal(data.runtime.browser.language, 'en-US');
  assert.equal(data.runtime.browser.webRTCPolicy, 'disable_non_proxied_udp');
  assert.equal(JSON.stringify(data).includes(password), false);
  const persisted = await fs.readFile(path.join(dataDir, 'profiles.json'), 'utf8');
  assert.equal(persisted.includes(password), false);
  pass('authenticated HTTP CONNECT with HTTPS, country check, timezone, locale, WebRTC policy and encrypted credentials');
  await api('navigate', `${base}/page`);
  await page.waitForTimeout(700);
  await page.getByRole('button', { name: 'Browser', exact: true }).click();
  const guestId = await app.evaluate(({ webContents }) => webContents.getAllWebContents().find(w => w.getURL().includes('/page')).id);
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  assert.equal((await api('getState')).runtime.zoom, 1.1);
  await app.evaluate(({ webContents }, id) => { const wc=webContents.fromId(id); wc.sendInputEvent({type:'keyDown',keyCode:'0',modifiers:['control']}); wc.sendInputEvent({type:'keyUp',keyCode:'0',modifiers:['control']}); }, guestId);
  await page.waitForTimeout(100);
  assert.equal((await api('getState')).runtime.zoom, 1);
  await page.getByRole('button', { name: 'Pop out', exact: true }).click();
  assert.equal((await api('getState')).runtime.detached, true);
  assert.equal(await app.evaluate(({ webContents }, id) => webContents.fromId(id).isDestroyed(), guestId), false);
  await api('browserAction', 'fullscreen'); await page.waitForTimeout(300);
  assert.equal((await api('getState')).runtime.fullscreen, true);
  await app.evaluate(({ webContents }, id) => webContents.fromId(id).sendInputEvent({type:'keyDown',keyCode:'Escape'}), guestId);
  await page.waitForTimeout(200);
  assert.equal((await api('getState')).runtime.fullscreen, false);
  const floatingReadings = await guest('({locale:navigator.language,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})');
  assert.equal(floatingReadings.locale, 'en-US'); assert.equal(floatingReadings.timezone, 'America/New_York');
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('#floating')).close());
  assert.equal((await api('getState')).runtime.detached, false);
  assert.equal(await app.evaluate(({ webContents }, id) => webContents.fromId(id).isDestroyed(), guestId), false);
  await capture('browser-controls.png');
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setContentSize(1060, 740));
  await capture('browser-controls-compact.png');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setContentSize(1440, 900));
  await app.evaluate(async ({webContents}, id) => { await webContents.fromId(id).executeJavaScript('document.documentElement.requestFullscreen()', true); }, guestId);
  await page.waitForTimeout(300);
  assert.equal((await api('getState')).runtime.detached, true);
  assert.equal((await api('getState')).runtime.fullscreen, true);
  assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>!w.webContents.getURL().endsWith('#floating')).isFullScreen()), false);
  await guest('document.exitFullscreen()'); await page.waitForTimeout(300);
  await api('browserAction', 'dock');
  pass('zoom keyboard/toolbar and floating full-screen/close retain the same regional browser');
  assert.equal(await guest("navigator.permissions.query({name:'camera'}).then(p=>p.state)"), 'denied');
  assert.equal(await guest("Notification.requestPermission()"), 'denied');
  assert.equal(await guest("fetch('https://192.168.1.1/').then(()=>false,()=>true)"), true);
  assert.equal(await guest("fetch('https://[::1]/').then(()=>false,()=>true)"), true);
  pass('camera and notifications deny by default; private network and loopback requests stay blocked');
  checkRateLimited = true;
  let limited = await api('verify');
  assert.equal(limited.runtime.status, 'ready');
  assert.match(limited.runtime.message, /region-check service.*429/);
  const beforeRetry = geoRequests;
  await api('verify'); assert.equal(geoRequests, beforeRetry, 'manual verification must respect Retry-After');
  checkRateLimited = false;
  await page.waitForTimeout(6200);
  assert.equal((await api('getState')).runtime.retryAt, undefined);
  assert.equal(await app.evaluate(({ webContents }, id) => webContents.fromId(id).isDestroyed(), guestId), false);
  pass('region-service 429 honors cooldown and automatically recovers without closing the page');
  tunnelRateLimited = true;
  await app.evaluate(async ({ webContents }, id) => webContents.fromId(id).session.closeAllConnections(), guestId);
  await guest("fetch('/limited').catch(()=>null)");
  assert.ok(rateLimitHits > 0);
  limited = await api('getState');
  assert.equal(limited.runtime.status, 'ready'); assert.match(limited.runtime.message, /proxy.*rate-limit/i);
  tunnelRateLimited = false;
  await page.waitForTimeout(6200);
  assert.equal((await api('getState')).runtime.status, 'ready');
  assert.equal((await api('getState')).runtime.retryAt, undefined);
  assert.equal(await app.evaluate(({ webContents }, id) => webContents.fromId(id).isDestroyed(), guestId), false);
  pass('upstream tunnel 429 preserves session and recovers through the same proxy');
  const nativeHints = await page.evaluate(() => navigator.userAgentData.toJSON());
  assert.deepEqual(await guest('navigator.userAgentData.toJSON()'), nativeHints, 'Regional preferences must preserve native Client Hints');
  const nativeHighHints = await page.evaluate(() => navigator.userAgentData.getHighEntropyValues(['architecture', 'bitness', 'platformVersion', 'fullVersionList', 'wow64']));
  assert.deepEqual(await guest("navigator.userAgentData.getHighEntropyValues(['architecture','bitness','platformVersion','fullVersionList','wow64'])"), nativeHighHints);
  assert.equal(browserHeaders.language, 'en-US');
  pass('regional overrides preserve native low/high-entropy Client Hints APIs and the configured HTTPS language');
  assert.equal(await guest('typeof window.regiondesk'), 'undefined');
  assert.equal(await guest('typeof require'), 'undefined');
  const worker = await guest("new Promise((resolve,reject) => { const w = new Worker('/worker.js'); w.onmessage = e => { w.terminate(); resolve(e.data); }; w.onerror = () => reject(new Error('Worker failed')); setTimeout(() => {w.terminate();reject(new Error('Worker timed out'));},5000); })");
  console.log('Worker regional readings:', JSON.stringify(worker));
  assert.equal(worker.language, 'en-US');
  assert.equal(worker.timezone, 'America/New_York');
  assert.deepEqual(worker.clientHints, nativeHints);
  const frame = await guest(`new Promise((resolve,reject) => { const f=document.createElement('iframe'); const receive=e=>{if(e.source===f.contentWindow){removeEventListener('message',receive);f.remove();resolve(e.data);}};addEventListener('message',receive);f.src='https://regiondesk-frame.test:${fixture.address().port}/frame';document.body.append(f);setTimeout(()=>{removeEventListener('message',receive);f.remove();reject(new Error('Frame timed out'));},5000);})`);
  assert.equal(frame.language, 'en-US');
  assert.equal(frame.timezone, 'America/New_York');
  assert.deepEqual(frame.clientHints, nativeHints);
  const dnsBlocked = await app.evaluate(async ({ session }) => { try { await session.defaultSession.resolveHost('example.com'); return false; } catch { return true; } });
  assert.equal(dnsBlocked, true, 'Chromium local DNS resolver should be disabled');
  pass('cross-site frame matches region; proxy resolves fixture hostnames while Chromium local DNS is blocked');
  const rtcCandidates = await guest(`new Promise(async resolve => { const p = new RTCPeerConnection({iceServers:[{urls:'stun:127.0.0.1:${stun.address().port}'}]}); const candidates=[]; p.onicecandidate = e => { if(e.candidate)candidates.push(e.candidate.candidate); }; p.createDataChannel('probe'); await p.setLocalDescription(await p.createOffer()); setTimeout(()=>{p.close();resolve(candidates);},1500); })`);
  assert.equal(directStunPackets, 0, 'WebRTC sent a direct UDP packet');
  assert.deepEqual(rtcCandidates, [], 'WebRTC exposed an unproxied ICE candidate');
  pass('worker regional preferences agree and WebRTC sends no direct STUN packets or host candidates');
  await guest("document.cookie='regiondesk=A; SameSite=Lax; max-age=3600'; localStorage.setItem('marker','A'); true");
  assert.equal(await guest("localStorage.getItem('marker')"), 'A');
  pass('embedded website has no Node or privileged app bridge');
  const geolocationDenied = await guest("new Promise(resolve => navigator.geolocation.getCurrentPosition(() => resolve(false), e => resolve(e.code === 1), {timeout:2000}))");
  assert.equal(geolocationDenied, true); pass('default geolocation permission denies coordinates');
  const firstTab = (await api('getState')).browsing.activeTabId;
  const browserProfile = (await api('getState')).profiles.find(p => p.id === a.id);
  await api('saveProfile', { ...browserProfile, blockTrackers: true });
  await api('verify'); await api('navigate', `${base}/page`);
  await waitGuest();
  await page.getByRole('button', { name: 'Bookmark this page', exact: true }).click();
  assert.equal((await api('getState')).browsing.bookmarks[0].url, `${base}/page`);
  await page.getByRole('button', { name: 'Find in page', exact: true }).click();
  await page.getByLabel('Find text', { exact: true }).fill('Local browser test');
  await page.waitForFunction(async () => (await window.regiondesk.getState()).runtime.find?.matches > 0);
  await page.getByRole('button', { name: 'Close find', exact: true }).click();
  await app.evaluate(({ webContents }, url) => {
    const wc = webContents.getAllWebContents().find(w => w.getURL() === url);
    wc.sendInputEvent({ type: 'keyDown', keyCode: 'f', modifiers: ['control'] });
    wc.sendInputEvent({ type: 'keyUp', keyCode: 'f', modifiers: ['control'] });
  }, `${base}/page`);
  await page.getByLabel('Find text', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Close find', exact: true }).click();
  assert.ok(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].contentView.children.some(view => view.getBounds().height > 100)), 'Find shortcut must keep the page visible');
  assert.equal(await guest("fetch('https://www.google-analytics.com/collect').then(()=>false,()=>true)"), true);
  assert.ok((await api('getState')).runtime.blockedTrackers >= 1);
  assert.equal((await api('getState')).runtime.status, 'ready');
  const disposable = await api('newTab', `${base}/reopen`);
  await api('closeTab', disposable.browsing.activeTabId);
  await page.getByRole('button', { name: 'Reopen closed tab', exact: true }).click();
  data = await api('getState');
  assert.equal(data.browsing.tabs.find(t => t.id === data.browsing.activeTabId).url, `${base}/reopen`);
  await api('closeTab', data.browsing.activeTabId); await api('selectTab', firstTab); await waitGuest();
  pass('bookmarks, find-in-page and closed-tab recovery work; tracker blocking preserves verified routing');
  await guest("globalThis.tabMarker='retained'; true");
  const secondState = await api('newTab', `${base}/next?tab=second`);
  const secondTab = secondState.browsing.activeTabId;
  await page.waitForTimeout(500);
  assert.equal((await api('getState')).browsing.tabs.length, 2);
  await api('selectTab', firstTab);
  assert.equal(await guest('globalThis.tabMarker'), 'retained');
  await page.locator(`[data-tab-id="${secondTab}"]`).dragTo(page.locator(`[data-tab-id="${firstTab}"]`));
  assert.deepEqual((await api('getState')).browsing.tabs.map(tab=>tab.id), [secondTab, firstTab]);
  await api('browserAction', 'detach');
  let floatingPage;
  for (let attempt=0; attempt<50; attempt++) { floatingPage=app.windows().find(w=>w.url().endsWith('#floating')); if (floatingPage) break; await page.waitForTimeout(100); }
  assert.ok(floatingPage, 'Floating browser shell must open');
  await floatingPage.getByRole('tab').first().waitFor();
  await floatingPage.locator(`[data-tab-id="${secondTab}"] [role=tab]`).click();
  assert.equal((await api('getState')).runtime.detached, true);
  assert.match((await api('getState')).runtime.url, /tab=second/);
  await floatingPage.locator(`[data-tab-id="${firstTab}"]`).dragTo(floatingPage.locator(`[data-tab-id="${secondTab}"]`));
  assert.deepEqual((await api('getState')).browsing.tabs.map(tab=>tab.id), [firstTab, secondTab]);
  await floatingPage.getByLabel('Website address').fill(`${base}/next?tab=floating`);
  await floatingPage.getByLabel('Website address').press('Enter'); await page.waitForTimeout(400);
  assert.match((await api('getState')).runtime.url, /tab=floating/);
  await floatingPage.getByLabel('Website address').fill('tab=second');
  await floatingPage.getByRole('option').click(); await page.waitForTimeout(400);
  assert.match((await api('getState')).runtime.url, /tab=second/);
  await assert.rejects(() => floatingPage.evaluate(() => window.regiondesk.createProfile()), /Untrusted/);
  const guestBounds = await app.evaluate(({ BrowserWindow }) => {
    const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('#floating'));
    return w.contentView.children.filter(v=>'webContents' in v && v.webContents.getURL().includes('tab=second')).map(v=>v.getBounds());
  });
  assert.ok(guestBounds[0].y >= 100, 'Page must sit below visible tabs and address controls');
  if (process.env.REGIONDESK_CAPTURE === '1') {
    await floatingPage.screenshot({path:path.join(review,'floating-tabs.png')});
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('#floating')).setContentSize(600,500));
    await page.waitForTimeout(200); await floatingPage.screenshot({path:path.join(review,'floating-tabs-compact.png')});
  }
  await floatingPage.getByRole('button', {name:'New tab',exact:true}).click();
  await floatingPage.getByRole('heading',{name:'New tab',exact:true}).waitFor();
  assert.equal((await api('getState')).browsing.tabs.length, 3);
  await floatingPage.getByRole('button',{name:'Close tab 3',exact:true}).click();
  pass('drag reorder works in both windows; floating tabs, address/history navigation and blank-tab controls are usable');
  await api('browserAction', 'dock');
  await api('selectTab', firstTab);
  await guest("window.open('/popup?tab=popup'); true"); await page.waitForTimeout(500);
  let tabState = (await api('getState')).browsing;
  assert.equal(tabState.tabs.length, 3);
  await api('closeTab', tabState.activeTabId); await api('selectTab', firstTab);
  assert.equal(await guest('globalThis.tabMarker'), 'retained');
  pass('multiple live tabs, popup tabs and floating tab switches preserve existing page state');
  await page.getByRole('button', { name: 'Browser', exact: true }).click();
  await page.getByLabel('Website address').fill('tab=second');
  await page.getByRole('listbox', { name: 'Address suggestions' }).waitFor();
  assert.equal(await page.getByRole('option').count(), 1);
  await page.getByLabel('Website address').press('ArrowDown');
  await page.getByLabel('Website address').press('Enter'); await page.waitForTimeout(500);
  assert.match((await api('getState')).runtime.url, /tab=second/);
  await api('navigate', `${base}/page`); await page.waitForTimeout(300);
  await capture('tabs.png');
  await page.getByRole('button', { name: 'History', exact: true }).first().click();
  await page.getByLabel('Search history').fill('tab=second');
  assert.equal(await page.locator('.history-list li').count(), 1);
  await capture('history.png');
  await api('removeHistory', `${base}/next?tab=second`);
  assert.equal((await api('getState')).browsing.history.some(entry=>entry.url.includes('tab=second')), false);
  await page.getByRole('button', { name: 'Browser', exact: true }).click();
  pass('profile history powers keyboard address suggestions and searchable removable history');

  assert.equal((await api('getState')).runtime.status, 'ready');
  checkRateLimited = true;
  await api('verify');
  await app.evaluate(() => { globalThis.realDateNow = Date.now; Date.now = () => globalThis.realDateNow() + 91_000; });
  await page.waitForTimeout(1300);
  assert.equal((await api('getState')).runtime.status, 'error');
  await assert.rejects(() => api('navigate', `${base}/page`), /Verify/);
  await app.evaluate(() => { Date.now = globalThis.realDateNow; delete globalThis.realDateNow; });
  checkRateLimited = false;
  await api('disconnect'); await api('verify');
  pass('rate limits do not extend verification lease; expired verification closes browsing');
  await api('browserAction', 'detach');
  const bState = await api('createProfile');
  assert.equal(await app.evaluate(({ BaseWindow }) => BaseWindow.getAllWindows().length), 1, 'Profile switching must close floating window');
  assert.equal(bState.browsing.tabs.length, 1); assert.equal(bState.browsing.tabs[0].url, ''); assert.deepEqual(bState.browsing.history, []);
  const b = bState.profiles.find(p => p.id === bState.activeId);
  await api('saveProfile', { ...b, permissions: {camera:true,microphone:false,notifications:true,clipboard:false,fullscreen:true}, name: 'United Kingdom', country: 'GB', city: 'London', locale: 'en-GB', timezone: 'Europe/London', latitude: 51.5074, longitude: -0.1278, locationPermission: 'configured', password, proxy: { ...a.proxy, host: '127.0.0.1', port: proxyPort, username, provider: 'Local verification fixture' } });
  country = 'GB'; data = await api('verify');
  assert.equal(data.runtime.status, 'ready', data.runtime.message);
  assert.equal(data.runtime.browser.timezone, 'Europe/London');
  assert.equal(data.runtime.browser.language, 'en-GB');
  await api('navigate', `${base}/page`); await page.waitForTimeout(500);
  assert.equal(await guest("localStorage.getItem('marker')"), null);
  assert.equal(await guest("document.cookie.includes('regiondesk=A')"), false);
  const position = await guest("new Promise(resolve => navigator.geolocation.getCurrentPosition(p => resolve({lat:p.coords.latitude,lon:p.coords.longitude}), e => resolve({error:e.code}), {timeout:5000}))");
  assert.equal(await guest("navigator.permissions.query({name:'camera'}).then(p=>p.state)"), 'granted');
  assert.equal(await guest("navigator.permissions.query({name:'microphone'}).then(p=>p.state)"), 'denied');
  assert.equal(await guest("Notification.requestPermission()"), 'granted');
  assert.equal(position.lat, 51.5074, JSON.stringify(position));
  pass('second profile isolates cookies/storage and applies UK locale, timezone and configured coordinates');
  await api('selectProfile', a.id); country = 'US';
  await api('verify'); await api('navigate', `${base}/page`); await page.waitForTimeout(500);
  assert.equal(await guest("localStorage.getItem('marker')"), 'A');
  assert.equal(await guest("document.cookie.includes('regiondesk=A')"), true);
  pass('returning to a profile restores only its own genuine session');
  const savedTabs = (await api('getState')).browsing;
  await app.close(); app = null;
  const requestsBeforeRestart = proxyRequests;
  await launch();
  const restoredTabs = (await api('getState')).browsing;
  assert.deepEqual(restoredTabs.tabs.map(({loaded,loading,...tab})=>tab), savedTabs.tabs.map(({loaded,loading,...tab})=>tab));
  assert.equal(restoredTabs.activeTabId, savedTabs.activeTabId);
  assert.ok(restoredTabs.tabs.every(tab=>!tab.loaded));
  assert.equal(proxyRequests, requestsBeforeRestart);
  pass('restart restores profile tab order/selection without any page request before verification');
  assert.equal((await api('getState')).runtime.status, 'locked');
  data = await api('verify'); assert.equal(data.runtime.status, 'ready', data.runtime.message);
  await api('navigate', `${base}/page`); await page.waitForTimeout(500);
  assert.equal(await guest("localStorage.getItem('marker')"), 'A');
  assert.equal(await guest("document.cookie.includes('regiondesk=A')"), true);
  pass('restart preserves encrypted proxy credentials and cookies but requires reverification');
  country = 'GB'; data = await api('verify');
  assert.equal(data.runtime.status, 'error'); assert.match(data.runtime.message, /mismatch/);
  await assert.rejects(() => api('navigate', `${base}/page`), /Verify/);
  pass('country mismatch closes and locks managed browsing');
  country = 'US'; await api('verify');
  overrideTimezone = 'America/Los_Angeles'; data = await api('verify');
  assert.equal(data.runtime.status, 'error'); assert.match(data.runtime.message, /Timezone mismatch/);
  await assert.rejects(() => api('navigate', `${base}/page`), /Verify/);
  pass('same-country timezone mismatch blocks browsing');
  overrideTimezone = ''; await api('verify');
  await new Promise(resolve => { for (const socket of tunnels) socket.destroy(); upstream.closeAllConnections(); upstream.close(resolve); });
  data = await api('verify'); assert.equal(data.runtime.status, 'error');
  await assert.rejects(() => api('navigate', `${base}/page`), /Verify/);
  assert.equal(directRequests, 0, 'unexpected direct request reached fixture');
  assert.ok(proxyRequests > 0);
  pass('proxy failure never falls back to a direct request');
  await api('disconnect');
  await fs.writeFile(path.join(review, 'verification.json'), JSON.stringify({ passes, proxyRequests, directRequests, authenticationChallenges, liveTikTok: 'NOT TESTED — no user account supplied', liveRegionalProxy: 'NOT TESTED — local fixtures only', timestamp: new Date().toISOString() }, null, 2));
  console.log(`Completed ${passes.length} desktop checks. Live TikTok and paid/free provider access were not tested.`);
} finally {
  if (app) await app.close().catch(() => {});
  for (const socket of tunnels) socket.destroy(); upstream.closeAllConnections(); upstream.close(); fixture.closeAllConnections(); fixture.close();
  stun.close();
}
